package rs.ac.bg.fon.ai.forme;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.TitledBorder;

import rs.ac.bg.fon.ai.domen.Kolac;
import rs.ac.bg.fon.ai.domen.Kupac;
import rs.ac.bg.fon.ai.domen.Poslasticar;
import rs.ac.bg.fon.ai.domen.Racun;
import rs.ac.bg.fon.ai.domen.StavkaRacuna;
import rs.ac.bg.fon.ai.forma.kupac.FormaNoviKupac;
import rs.ac.bg.fon.ai.forma.kupac.FormaPretragaKupaca;
import rs.ac.bg.fon.ai.forme.kolac.FormaKolac;
import rs.ac.bg.fon.ai.kontroler.KlijentKontroler;
import rs.ac.bg.fon.ai.modeli.ModelTabeleStavkaRacuna;
import rs.ac.bg.fon.ai.sesija.Sesija;

import javax.swing.border.EtchedBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JComboBox;

public class GlavnaForma extends javax.swing.JFrame {
    
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Poslasticar ulogovaniPoslasticar;
	private double ukupanIznos;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.ulogovaniPoslasticar = Sesija.getInstance().getUlogovaniPoslasticar();
        lblUlogovani.setText("Ulogovani poslastičar: " + ulogovaniPoslasticar.toString());
        Sesija.getInstance().setGlavnaForma(this);
        
        popuniKolace();
        popuniKupce();
        
        setTitle("Poslasticarnica");
        txtUkupanIznos.setEditable(false);
        tblStavke.setModel(new ModelTabeleStavkaRacuna());
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                      
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtUkupanIznos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbKolac = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnKupac = new javax.swing.JMenu();
        miNoviKupac = new javax.swing.JRadioButtonMenuItem();
        miPretraga = new javax.swing.JRadioButtonMenuItem();
        mnKolac = new javax.swing.JMenu();
        miKolac = new javax.swing.JRadioButtonMenuItem();
        mnOdjava = new javax.swing.JMenu();
        miOdjava = new javax.swing.JRadioButtonMenuItem();
        cmbKupac = new JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, new Color(255, 255, 255), new Color(160, 160, 160)), "Ra\u010Dun", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));

        jLabel2.setText("Ukupan iznos:");

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sačuvaj račun");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnSacuvajActionPerformed(evt);
            }
        });

        txtUkupanIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        jPanel2.setBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, new Color(255, 255, 255), new Color(160, 160, 160)), "Stavka ra\u010Duna", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));

        jLabel6.setText("Kolač:");

        jLabel8.setText("Količina:");

        cmbKolac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKolac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
            	
            }
        });
        
        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKupac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
            	
            }
        });
        
        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDodajStavkuActionPerformed(evt); 
            }
        });

        btnObrisiStavku.setText("Obriši stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbKolac, 0, 455, Short.MAX_VALUE)
                            .addComponent(txtKolicina))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbKolac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        
        jLabel3_1 = new JLabel();
        jLabel3_1.setText("Kupac:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(68)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(726))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel3_1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        					.addGap(33)
        					.addComponent(cmbKupac, GroupLayout.PREFERRED_SIZE, 709, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(24)
        					.addComponent(jLabel2)
        					.addGap(18)
        					.addComponent(txtUkupanIznos, GroupLayout.PREFERRED_SIZE, 705, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(151)
        					.addComponent(btnSacuvaj, GroupLayout.PREFERRED_SIZE, 463, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(8)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3_1)
        				.addComponent(cmbKupac, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtUkupanIznos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnSacuvaj, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        mnKupac.setText("Kupac");

        miNoviKupac.setSelected(true);
        miNoviKupac.setText("Novi kupac");
        miNoviKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviKupacActionPerformed(evt);
            }
        });
        mnKupac.add(miNoviKupac);

        miPretraga.setSelected(true);
        miPretraga.setText("Pretraga");
        miPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaActionPerformed(evt);
            }
        });
        mnKupac.add(miPretraga);

        jMenuBar1.add(mnKupac);

        mnKolac.setText("Kolac");

        miKolac.setSelected(true);
        miKolac.setText("Upravljanje kolačem");
        miKolac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	mnKolacActionPerformed(evt);
            }
        });
        mnKolac.add(miKolac);

        jMenuBar1.add(mnKolac);

        mnOdjava.setText("Odjava");

        miOdjava.setSelected(true);
        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 miOdjavaActionPerformed(evt);
            }
        });
        mnOdjava.add(miOdjava);

        jMenuBar1.add(mnOdjava);

        setJMenuBar(jMenuBar1);
        
        lblUlogovani = new JLabel("Poslasticar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 817, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(lblUlogovani, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(lblUlogovani)
        			.addGap(13)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }                   
    
    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Kolac kolac = (Kolac) cmbKolac.getSelectedItem();

            if (kolac == null) {
                JOptionPane.showMessageDialog(this, "Morate izabrati kolač!");
                return;
            }

            if (txtKolicina.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti količinu!");
                return;
            }

            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina <= 0) {
                JOptionPane.showMessageDialog(this, "Količina mora biti veća od nula!");
                return;
            }

            ModelTabeleStavkaRacuna model = (ModelTabeleStavkaRacuna) tblStavke.getModel();

            if (model.postojiKolac(kolac)) {
                JOptionPane.showMessageDialog(this, "Izabrani kolač je već dodat u račun!");
                return;
            }

            double cena = kolac.getCena();
            double iznos = cena * kolicina;

            StavkaRacuna stavka = new StavkaRacuna(null,0,cena,kolicina,iznos,kolac);

            model.dodajStavku(stavka);

            txtUkupanIznos.setText(String.valueOf(model.vratiUkupanIznos()));

            txtKolicina.setText("");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Količina mora biti ceo broj!");
        }
    }
    
    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {

        int selektovaniRed = tblStavke.getSelectedRow();

        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku koju želite da obrišete!");
            return;
        }

        ModelTabeleStavkaRacuna model = (ModelTabeleStavkaRacuna) tblStavke.getModel();
        model.obrisiStavku(selektovaniRed);

        txtUkupanIznos.setText(String.valueOf(model.vratiUkupanIznos()));
    }
    
    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {

        try {

            Kupac kupac = (Kupac) cmbKupac.getSelectedItem();

            if (kupac == null) {
                JOptionPane.showMessageDialog(this, "Morate izabrati kupca!");
                return;
            }

            ModelTabeleStavkaRacuna model = (ModelTabeleStavkaRacuna) tblStavke.getModel();

            ArrayList<StavkaRacuna> stavke = model.getLista();

            if (stavke == null || stavke.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Račun mora imati barem jednu stavku!");
                return;
            }

            double ukupanIznos = model.vratiUkupanIznos();

            Racun racun = new Racun(null,new Date(),ukupanIznos,ulogovaniPoslasticar,kupac,stavke);

            KlijentKontroler.getInstance().ubaciRacun(racun);

            JOptionPane.showMessageDialog(this,"Račun je uspešno sačuvan!");

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,"Greška prilikom čuvanja računa: "+ ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKolac;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButtonMenuItem miKolac;
    private javax.swing.JRadioButtonMenuItem miNoviKupac;
    private javax.swing.JRadioButtonMenuItem miOdjava;
    private javax.swing.JRadioButtonMenuItem miPretraga;
    private javax.swing.JMenu mnKolac;
    private javax.swing.JMenu mnOdjava;
    private javax.swing.JMenu mnKupac;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtUkupanIznos;
    private javax.swing.JTextField txtKolicina;
    private JLabel jLabel3_1;
	private javax.swing.JLabel lblUlogovani;
    // End of variables declaration                   

    private void popuniKolace() {
        try {
            ArrayList<Kolac> kolaci = KlijentKontroler.getInstance().vratiSveKolace();
            cmbKolac.removeAllItems();
            for (Kolac kolac : kolaci) {
                cmbKolac.addItem(kolac);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    } //Logger.getLogger(FormaNoviPolaznik.class.getName()).log(Level.SEVERE, null, ex);
    
    private void popuniKupce() {
        try {

            ArrayList<Kupac> kupci = KlijentKontroler.getInstance().vratiSveKupce();

            cmbKupac.removeAllItems();

            for (Kupac kupac : kupci) {
                cmbKupac.addItem(kupac);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void mnKolacActionPerformed(java.awt.event.ActionEvent evt) {
        FormaKolac forma = new FormaKolac();
        forma.setVisible(true);
    }
    
    private void miNoviKupacActionPerformed(java.awt.event.ActionEvent evt) {
        FormaNoviKupac forma = new FormaNoviKupac(this, true);
        forma.setVisible(true);
    }
    
    private void miPretragaActionPerformed(java.awt.event.ActionEvent evt) {
        FormaPretragaKupaca forma = new FormaPretragaKupaca(this, true);
        forma.setVisible(true);
    }
    
    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {

        try {

            KlijentKontroler.getInstance().logout(ulogovaniPoslasticar);

            Sesija.getInstance().setUlogovaniPoslasticar(null);

            JOptionPane.showMessageDialog(this,"Uspešno ste se odjavili sa sistema!");

            this.dispose();

            LoginForma loginForma = new LoginForma();
            loginForma.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Greška prilikom odjavljivanja: "+ ex.getMessage());
        }
    }
}

