package rs.ac.bg.fon.ai.forme;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import rs.ac.bg.fon.ai.domen.Poslasticar;
import rs.ac.bg.fon.ai.kontroler.KlijentKontroler;
import rs.ac.bg.fon.ai.sesija.Sesija;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPasswordField;
import java.awt.Dimension;

public class LoginForma extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form LoginForma
     */
    public LoginForma() {
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Login forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();
        btnOtkazi.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnOtkaziActionPerformed(e);
        	}
        });
        btnLogin = new javax.swing.JButton();
        btnLogin.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnLoginActionPerformed(e);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnOtkazi.setText("Otkaži");

        btnLogin.setText("Login");
        
        txtPassword = new JPasswordField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnOtkazi)
        					.addGap(80)
        					.addComponent(btnLogin))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addGap(18))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addGap(20)))
        					.addGap(11)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtUsername, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        						.addComponent(txtPassword, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
        			.addGap(160))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(31)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(37)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnOtkazi)
        				.addComponent(btnLogin))
        			.addContainerGap(79, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }            
    
    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    	Sesija.getInstance().close();
    	System.exit(0); 
        
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	 
        if (txtUsername.getText().isEmpty()
                || String.valueOf(txtPassword.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Korisničko ime i lozinka moraju biti popunjeni!");
            return;
        }
 
        Poslasticar ps = new Poslasticar();
        ps.setKorisnickoIme(txtUsername.getText());
        ps.setSifra(new String(txtPassword.getPassword()));
 
        try {
            Poslasticar ulogovani = KlijentKontroler.getInstance().login(ps);
            Sesija.getInstance().setUlogovaniPoslasticar(ulogovani);
            JOptionPane.showMessageDialog(this, "Korisničko ime i šifra su ispravni.");
 
            try {
                new GlavnaForma().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne može da se otvori glavna forma i meni",
                        "Greška", JOptionPane.ERROR_MESSAGE);
            }
 
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Server nije pokrenut!");
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Korisničko ime i šifra nisu ispravni.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtUsername;
    private JPasswordField txtPassword;
}

