package rs.ac.bg.fon.ai.forme;

import javax.swing.JOptionPane;

import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Properties;
import java.util.logging.Logger;
import java.util.logging.Level;

public class KonfiguracijaBaze extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	public KonfiguracijaBaze() {
	    initComponents();
	    
	    setLocationRelativeTo(null);
	    setTitle("Unos novih konfiguracionih podataka za bazu");
	    popuniPolja();
	    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                             
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("URL:");

        jLabel2.setText("USERNAME:");

        jLabel3.setText(" PASSWORD:");

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(txtUser)
                    .addComponent(txtUrl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnOtkazi)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }                                                        

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        this.dispose();
        
    }                                         

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            String urlInput = txtUrl.getText().trim();
            String username = txtUser.getText().trim();
            String password = new String(txtPass.getPassword());

            if (urlInput.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Unesite URL!");
                return;
            }

            Path cfg = Paths.get("konfiguracija.properties");
            Properties prop = new Properties();

            if (Files.exists(cfg)) {
                try (InputStream in = Files.newInputStream(cfg)) {
                    prop.load(in);
                }
            }

            prop.setProperty("url", urlInput);
            prop.setProperty("username", username);
            prop.setProperty("password", password);

            try (OutputStream out = Files.newOutputStream(cfg,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING,
                    StandardOpenOption.WRITE)) {
                prop.store(out, "Konfiguracija baze");
            }

            JOptionPane.showMessageDialog(this, "Konfiguracija uspešno sačuvana.");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri čuvanju konfiguracije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
        }
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfiguracijaBaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfiguracijaBaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfiguracijaBaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfiguracijaBaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfiguracijaBaze().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUser;
    // End of variables declaration                   

    private void popuniPolja() {
        try {
            Properties properties = new Properties();
            Path cfg = Paths.get("konfiguracija.properties");

            if (Files.exists(cfg)) {
                try (InputStream in = Files.newInputStream(cfg)) {
                    properties.load(in);
                }
            }

            //izvlacenje vrednosti
            String url = properties.getProperty("url", "jdbc:mysql://localhost:3308/poslasticarnica_ps");
            String username = properties.getProperty("username", "");
            String password = properties.getProperty("password", "");

            //popunjavanje polja na formi
            txtUrl.setText(url);
            txtUser.setText(username);
            txtPass.setText(password);

        } catch (Exception ex) {
            Logger.getLogger(KonfiguracijaBaze.class.getName()).log(Level.WARNING, "Ne mogu da učitam konfiguraciju", ex);
            txtUrl.setText("jdbc:mysql://localhost:3308/poslasticarnica_ps");
            txtUser.setText("");
            txtPass.setText("");
        }
        
    }
}
