package rs.ac.bg.fon.ai.forme;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.niti.PokreniServer;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class KonfiguracijaPorta extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final ServerskaForma parent;
    
    /**
     * Creates new form KonfiguracijaPorta
     */
    public KonfiguracijaPorta(ServerskaForma parent) {
        initComponents();
        
        this.parent = parent;
        setLocationRelativeTo(null);
        setTitle("Promena porta");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                           
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Port:");

        txtPort.setText("9000");

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(61)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(btnSacuvaj, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnOtkazi, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(txtPort, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(43)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addComponent(btnOtkazi)
        			.addGap(18)
        			.addComponent(btnSacuvaj)
        			.addContainerGap(145, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }                       

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
    }                                         

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int port = Integer.parseInt(txtPort.getText().trim());
            if (port < 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port mora biti između 0 i 65535!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Path cfg = Paths.get("konfiguracija.properties");
            Properties prop = new Properties();

            if (java.nio.file.Files.exists(cfg)) {
                try (java.io.InputStream in = java.nio.file.Files.newInputStream(cfg)) {
                    prop.load(in);
                }
            }

            prop.setProperty("port", String.valueOf(port));

            try (OutputStream out = Files.newOutputStream(cfg)) {
                prop.store(out, "Ažurirana konfiguracija porta");
            }

            PokreniServer noviServer = new PokreniServer(port);
            noviServer.start();
            parent.azurirajStatus(noviServer, port); 

            JOptionPane.showMessageDialog(this, "Server je pokrenut na portu " + port + ".", "OBAVEŠTENJE", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Port mora biti broj!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom čuvanja porta!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
        }
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPort;
    // End of variables declaration                   
}
