package rs.ac.bg.fon.ai.forme;

import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.niti.PokreniServer;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

public class ServerskaForma extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form ServerskaForma
     */
    
    private PokreniServer ps;
    
    public ServerskaForma() {
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Pokretanje servera");
        lblStatus.setText("Server nije pokrenut");
        btnZaustavi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                           
    private void initComponents() {

        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miBaze = new javax.swing.JMenuItem();
        miPorta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokreni.setText("POKRENI SERVER");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("ZAUSTAVI SERVER");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        jLabel1.setText("STATUS:");

        lblStatus.setText("jLabel2");

        jMenu1.setText("Konfiguracija");

        miBaze.setText("Baze");
        miBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBazeActionPerformed(evt);
            }
        });
        jMenu1.add(miBaze);

        miPorta.setText("Porta");
        miPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPortaActionPerformed(evt);
            }
        });
        jMenu1.add(miPorta);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(41, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addGap(24)
        			.addComponent(lblStatus, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(103)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(btnPokreni, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnZaustavi, Alignment.LEADING))
        			.addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(50)
        			.addComponent(btnPokreni, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnZaustavi, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        			.addGap(50)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(lblStatus))
        			.addContainerGap(74, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }                

    private void miBazeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        KonfiguracijaBaze kb = new KonfiguracijaBaze();
        kb.setVisible(true);
    }                                      

    private void miPortaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        new KonfiguracijaPorta(this).setVisible(true);
    }                                       

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            ps = new PokreniServer(9000);
            ps.start();
            lblStatus.setText("Server je pokrenut na portu 9000");
            btnPokreni.setEnabled(false);
            btnZaustavi.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri pokretanju!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {                                            
        ps.zaustaviServer();

        JOptionPane.showMessageDialog(this, "Server je uspešno ugašen.", "GAŠENJE PROGRAMA", JOptionPane.INFORMATION_MESSAGE);
        lblStatus.setText("Server je ugašen!");
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);

        ps = null;
        dispose();
        System.exit(0);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuItem miBaze;
    private javax.swing.JMenuItem miPorta;
    // End of variables declaration                   

    void azurirajStatus(PokreniServer noviServer, int port) {
        this.ps = noviServer;
        lblStatus.setText("Server je pokrenut na portu " + port);
        btnPokreni.setEnabled(false);
        btnZaustavi.setEnabled(true);
    }
}